sudo: false
language: go

go:
  - 1.10.x

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - go get github.com/mattn/goveralls
  - go get github.com/lawrencewoodman/roveralls

install:
  - dep ensure --vendor-only -v

script:
  - go get golang.org/x/lint/golint
  - make check
  - make test
  - make build.docker
  - roveralls -ignore cmd/e2e
  - goveralls -v -coverprofile=roveralls.coverprofile -service=travis-ci
