version: "2017-09-20"
pipeline:
- id: build
  overlay: machinery/go-overlay
  type: script
  env:
    GOPATH: /go
  working_dir: /go/src/github.com/zalando-incubator/stackset-controller
  commands:
  - desc: install deps
    cmd: |
      go get -u golang.org/x/lint/golint
      dep ensure -v -vendor-only
  - desc: test
    cmd: |
      export PATH=$GOPATH/bin:$PATH
      make check
      make test
  - desc: build
    cmd: |
      make build.docker
  - desc: push
    cmd: |
      if [[ $CDP_TARGET_BRANCH == master && ! $CDP_PULL_REQUEST_NUMBER ]]; then
        IMAGE=registry-write.opensource.zalan.do/teapot/stackset-controller
      else
        IMAGE=registry-write.opensource.zalan.do/teapot/stackset-controller-test
      fi
      IMAGE=$IMAGE VERSION=$CDP_BUILD_VERSION make build.push
