apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: stacksets.zalando.org
spec:
  group: zalando.org
  version: v1
  scope: Namespaced
  names:
    kind: StackSet
    singular: stackset
    plural: stacksets
  subresources:
    # status enables the status subresource.
    status: {}
