apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: stacks.zalando.org
spec:
  group: zalando.org
  version: v1
  scope: Namespaced
  names:
    kind: Stack
    singular: stack
    plural: stacks
  subresources:
    # status enables the status subresource.
    status: {}
